use_frameworks!

platform :ios, '9.0'

target 'LXNetworking_Example' do
  pod 'LXNetworking', :path => '../'

  target 'LXNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
